import React, { createContext, useState, useContext } from 'react';

const translations = {
  ko: {
    // ==================== 🏠 공통 UI (Common) ====================
    home: "🏠 홈",
    login: "로그인",
    logout: "로그아웃",
    signup: "회원가입",
    myWallet: "내 지갑",
    balance: "보유 자산",
    my_point: "내 자산",
    cancel: "취소",
    confirm: "확인",
    close: "닫기",
    loading: "로딩 중...",
    back: "돌아가기",
    serverCheck: "🚧 서버 점검 중",
    banned: "🚫 차단된 계정입니다.",
    waitingApproval: "⏳ 승인 대기 중",
    inputEmail: "이메일을 입력하세요",
    inputPw: "비밀번호",
    inputName: "이름 (닉네임)",
    fail: "실패",
    success: "성공",
    
    // ==================== 👮 관리자 & 제재 (Admin & Sanction) ====================
    ad_title: "👮 통합 관리자 페이지",
    ad_tab_notice: "📢 공지",
    ad_tab_users: "👥 유저",
    ad_tab_sanction: "🚨 제재",
    ad_tab_history: "📜 내역",
    ad_tab_server: "🚧 서버",
    ad_tab_features: "⚙️ 기능",
    ad_tab_wishbox: "🧞‍♂️ 소원함",
    
    ad_notice_title: "메인 공지 설정",
    ad_notice_ph: "내용 입력...",
    ad_save: "💾 저장",
    ad_report_rank: " 현상수배(신고누적)",
    reset_report: "🔄 신고 초기화",
    reset_report_confirm: "신고 횟수를 모두 0으로 초기화하시겠습니까?",
    ad_no_report: "신고된 유저가 없습니다. (클린)",
    ad_search_user: "유저 닉네임 검색...",
    ad_report_cnt: "신고",
    ban_gacha: "가챠 정지",
    ad_lift_ban: "정지 해제",
    ad_state_banned: "⛔ 제재 중",
    ad_state_normal: "✅ 정상",
    ad_tier: "티어",
    ad_demote: "강등",
    ad_promote: "승격",
    ad_tier_change: "티어 변경",
    confiscate: "재산 몰수",
    ad_input_confiscate: "몰수",
    ad_confiscate_amount: "몰수할 금액을 입력하세요",
    ad_input_num: "숫자만 입력하세요",
    ad_total_asset: "서버 총 자산",
    ad_user_cnt: "현재 가입 유저",
    ad_approve: "승인",
    ad_cancel_approve: "승인 취소",
    ad_ban_confirm: "밴/해제 하시겠습니까?",
    ad_point_confirm: "포인트를 지급/차감 하시겠습니까?",
    ad_server_status: "현재 서버 상태",
    ad_open_server: "✅ 서버 열기",
    ad_close_server: "🛑 서버 닫기",
    ad_open_confirm: "서버를 여시겠습니까?",
    ad_close_confirm: "서버를 닫으시겠습니까?",
    ad_feature_control: "시스템 기능 제어",
    ad_refresh_all: "전체 유저 새로고침",
    ad_refresh_confirm: "모든 유저에게 새로고침 신호를 보내시겠습니까?",
    ad_history_title: "최근 거래 내역 (50건)",
    ad_confirm: "실행하시겠습니까",
    lift_date: "해제 일시",
    gacha_banned_msg: "🚫 가챠 이용이 정지되었습니다.",
    
    // 🔥 [추가] 관리자 신규 기능
    ad_wish_list: "도착한 소원들",
    ad_no_wish: "도착한 소원이 없습니다.",
    ad_audit_btn: "🔍 장부검사",
    ad_audit_suspicious: "🚨 조작 의심!!",
    ad_audit_normal: "✅ 정상 계정",
    ad_audit_diff: "오차",
    ad_sync_posts: "🔄 게시글 칭호 동기화",
    ad_sync_confirm: "모든 게시글의 작성자 정보를 현재 유저 정보로 덮어씌웁니다.",

    // ==================== 💰 베팅 & 재화 (Betting & Money) ====================
    inputBet: "베팅 금액 입력",
    alertInputBet: "베팅 금액을 입력하세요!",
    alertNoMoney: "포인트가 부족합니다!",
    alertError: "오류 발생",
    h_bet: "베팅",
    h_gain: "획득",
    h_result: "결과",

    // ==================== 🔔 알림 (Notification) ====================
    h_noti: "알림",
    h_no_noti: "새로운 알림이 없습니다.",
    alert_unread: "안 읽은 알림이 {n}개 있습니다!",
    noti_clear: "알림 모두 지우기",
    noti_clear_confirm: "모든 알림을 삭제하시겠습니까?",
    noti_like: "님이 회원님의 글을 좋아합니다.",
    noti_comment: "님이 회원님의 글에 댓글을 남겼습니다.",
    noti_reply: "님이 회원님의 댓글에 답글을 남겼습니다.",

    // ==================== 🚫 제한 및 차단 (Limits) ====================
    daily_limit_msg: "오늘 남은 쪽지: {n}회",
    daily_limit_report: "오늘 남은 신고: {n}회",
    limit_reached: "오늘 횟수를 모두 소진했습니다.",

    // ==================== 🔝 헤더 & 메뉴 (Header & Menu) ====================
    h_attack: "핵공격",
    h_gacha: "가챠",
    h_transfer: "송금",
    h_history: "기록",
    h_mailbox: "쪽지",
    h_report: "신고",
    h_nuke_ask: "⚔️ 핵폭탄을 발사하시겠습니까?",
    h_nuke_desc: "내 전 재산의 절반을 사용하여 랜덤 유저 1명을 타격합니다.",
    h_nuke_no_target: "공격할 대상이 없습니다.",
    h_nuke_min: "핵폭탄을 발사하려면 최소 100원은 있어야 합니다.",
    h_nuke_hit: "🎯 [명중]",
    h_nuke_hit_msg: "님에게 핵폭탄이 떨어졌습니다!",
    h_nuke_damage: "피해량",
    h_locked: "🔒 현재 관리자가 이 기능을 비활성화했습니다.",

    // ==================== 🎮 게임 로비 (Game Lobby) ====================
    lobbyTitle: "🎮 게임 로비",
    roomTitlePlaceholder: "방 제목을 입력하세요 (선택)",
    betAmount: "베팅 금액",
    createRoom: "방 만들기",
    waiting: "대기 중인 방이 없습니다.",
    enter: "입장하기",
    full: "만원",
    participate: "참가하기",
    g_omok: "오목",
    g_rps: "가위바위보",
    g_soccer: "승부차기",
    g_typing: "타자 대결",
    g_memory: "카드 뒤집기",
    g_reaction: "반응속도",
    g_apple: "사과게임",

    // ==================== 🎮 게임 공통 (Game Common) ====================
    gameZone: "🎮 GAME ZONE",
    rank: "🏆 랭킹",
    updateRank: "🔄 랭킹 업데이트",
    notice: "📢 ",
    adminOnly: "👑 관리자 전용",
    adminPage: "👥 관리자페이지",
    waitingChallenger: "👥 도전자 입장 대기...",
    deleteRoom: "방 삭제",
    destroyRoom: "🏠 방 폭파",
    playerJoined: "👋 참가자가 들어왔습니다!",
    readyBtn: "준비 완료 (READY)",
    ready: "준비 완료",
    cancelReady: "준비 취소",
    waitingReady: "참가자의 준비를 기다리는 중...",
    allReady: "✅ 모든 준비 완료!",
    gameStart: "게임 시작",
    restart: "다시 하기",
    startWait: "방장이 시작하면 게임이 진행됩니다.",
    exit: "나가기",
    win: "🎉 승리!",
    draw: "무승부!",
    lose: "패배...",
    result: "결과",
    notEnough: "인원 부족",
    oneMore: "🔄 한 판 더",
    waitHost: "방장 대기중...",
    waitUser: "참가자 대기중...",

    // ==================== 🕹️ 게임 이름 (Game Names) ====================
    pvp: "⚔️ 1:1 (PvP)",
    cafe: "👑 테토카페",
    oddEven: "🎲 홀짝",
    slot: "🎰 슬롯",
    rps: "✌️ 가위바위보",
    blackjack: "🃏 블랙잭",
    angelDemon: "🎡 천사악마",
    ladder: "🎢 다리다리",
    mines: "💣 지뢰찾기",
    graph: "🚀 그래프",
    highlow: "🃏 하이로우",
    european: "🎡 유러피언",
    ostrich: "🦩 타조 게임",
    apple: "🍎 사과게임",
    highway: "🚗 꼬라박아 장용준처럼",
    stack: "🏗️ 네온 스택 타워",
    newBadge: "NEW!",

    // 🔥 [추가] 2048 게임
    g_2048_title: "🧩 2048 챌린지",
    g_2048_desc: "타일을 합쳐 높은 숫자를 만드세요!",
    g_2048_rule: "게임 오버 시 '가장 높은 숫자'에 따라 배당이 지급됩니다.",
    g_2048_max: "최대 타일",
    g_2048_score: "점수",
    g_2048_payout: "📊 배당률표 (최대 타일 기준)",
    g_2048_my_asset: "내 자산",
    g_2048_gameover: "게임 오버",
    g_2048_win: "축하합니다!",
    g_2048_fail: "실패...",

    // 🔥 [추가] 수박 게임
    g_suika_title: "🍉 수박 게임",
    g_suika_score: "점수",
    g_suika_next: "다음",
    g_suika_rule: "과일을 합쳐 수박을 만들고 고득점을 노리세요!",

    // 🔥 [추가] 테트리스
    g_tetris_title: "🧱 테트리스",
    g_score: "점수",
    g_level: "레벨",
    g_lines: "줄",
    g_hold: "보관",
    g_next: "다음",
    g_paused: "일시정지",
    g_resume: "계속하기",
    playAgain: "다시하기",
    g_hold_btn: "저장 (C)",
    g_drop_btn: "떨구기 (Spc)",
    g_paused_btn: "일시정지 (P)",
    probTable: "📊 배당률표",

    // ==================== 🍏 사과 게임 (Apple Game) ====================
    ag_title: "🍏 사과 게임",
    ag_bet: "1. 베팅 금액",
    ag_diff: "2. 목표 난이도",
    ag_start: "도전하기",
    ag_goal: "목표",
    ag_score: "점수",
    ag_success: "🎉 성공!",
    ag_fail: "😭 실패..",
    ag_cheat: "🚫 부정행위 감지! (시간 조작)",
    ag_disqualify: "이탈로 인한 실격 (포인트 소멸)",

    // ==================== 🏆 상점 (Shop) ====================
    shop: "🏆 상점",
    shopTitle: "🏆 상점",
    shopBalance: "보유 자산",
    buy: "구매",
    nickChange: "🏷️ 닉네임 변경권",
    nickDesc: "새로운 신분으로 세탁하세요.",
    blackMarket: "😈 암시장",
    shopClosed: "🔒 암시장이 폐쇄되었습니다",
    demoteR1: "📉 랜덤1단 강등",
    demoteR2: "📉 랜덤2단 강등",
    demoteSelf: "(나 포함)",
    demoteNoSelf: "(나 제외)",
    demoteBomb1: "💣 랜덤1단 강등",
    demoteBomb2: "💣 랜덤2단 강등",
    sniper: "🎯 저격 강등",
    sniperDesc: "(닉네임 지정 / 2단계 하락)",
    sniperTitle: "🎯 저격 대상 검색",
    searchNick: "닉네임 입력",
    search: "🔍 검색",
    doDemote: "강등시키기",
    noResult: "검색 결과가 없습니다.",
    currentTier: "현재 티어",
    upgrade: "승급 ▲",
    alertNick: "변경할 닉네임을 입력하세요:",
    alertCost: "비용",
    alertComplete: "완료!",
    alertTargetNone: "강등시킬 대상이 없습니다.",
    alertSniperConfirm: "님을 2단계 강등시키겠습니까?",
    // 🔥 [추가] 소원권 관련
    wishTicket: "🧞‍♂️ 소원권",
    wishDesc: "관리자에게 소원을 빕니다. (전재산 50%)",
    wish_min_asset: "최소 10억 이상의 자산이 있어야 구매할 수 있습니다.",
    wish_input_ph: "이루고 싶은 소원을 적어주세요.(안들어줄수도)",
    wish_confirm: "정말 소원을 비시겠습니까?",
    wish_success: "소원이 관리자에게 전달되었습니다!",

    // ==================== 💸 송금 (Transfer) ====================
    transferTitle: "💸 포인트 송금",
    transferDesc: "친구에게 포인트를 선물하세요.",
    myBalance: "내 잔액",
    searchReceiver: "받는 사람 검색",
    searchPlaceholder: "닉네임 앞글자 입력",
    searchBtn: "검색",
    select: "선택",
    sendAmount: "보낼 금액",
    sendBtn: "보내기 🚀",
    sending: "송금 진행 중...",
    alertSendConfirm: "님에게",
    alertSendConfirm2: "원을 보내시겠습니까?",
    alertSelf: "자신에게는 보낼 수 없습니다.",
    alertNoReceiver: "받는 사람 닉네임을 입력하세요!",

    // ==================== 📬 쪽지함 (Mailbox) ====================
    mb_title: "📬 쪽지함",
    mb_inbox: "받은 쪽지",
    mb_sent: "보낸 쪽지",
    mb_write: "쪽지 쓰기",
    mb_sender: "보낸 사람",
    mb_receiver: "받는 사람",
    mb_content: "내용",
    mb_date: "날짜",
    mb_read: "읽음",
    mb_unread: "안 읽음",
    mb_no_msg: "쪽지가 없습니다.",
    mb_send_btn: "보내기",
    mb_cancel: "취소",
    mb_search_user: "유저 검색 (닉네임)",
    mb_search_res: "검색 결과",
    mb_send_success: "쪽지를 보냈습니다!",
    mb_delete_confirm: "쪽지를 삭제하시겠습니까?",
    mb_reply: "답장",
    mb_to: "에게",

    // ==================== 🚨 신고 (Report) ====================
    r_title: "🚨 불량 유저 신고",
    r_step1: "1. 신고할 유저를 검색하세요",
    r_step2: "2. 신고 사유를 선택하세요",
    r_reason_input: "구체적인 사유를 적어주세요...",
    r_submit: "신고하기",
    r_complete: "신고가 접수되었습니다.",
    r_prev: "이전",
    r_target: "대상:",
    r_confirm_ask: "님을 신고하시겠습니까?",
    r_reason_1: "욕설/비방",
    r_reason_2: "사기/먹튀",
    r_reason_3: "도배/홍보",
    r_reason_4: "성적인 발언",
    r_reason_5: "직접 입력",
    r_admin_fail: "관리자 정보를 찾을 수 없습니다.",

    // ==================== 📜 기록 (History) ====================
    history: "📜 기록",
    log_gacha: "가챠",
    log_transfer: "송금",
    log_deposit: "입금",
    log_game: "게임",
    log_attack: "공격",
    log_hit: "피격",
    log_sniper: "저격",
    log_no_data: "기록이 없습니다.",

    // ==================== 🕵️ 계정 찾기 (Find Account) ====================
    faTitle: "🕵️ 계정 찾기",
    fa_findId: "ID 검색",
    fa_findPw: "비밀번호 찾기",
    fa_name: "가입 시 입력한 이름",
    fa_email: "가입한 이메일 주소",
    fa_send: "재설정 메일 발송",
    fa_found: "✅ 찾은 아이디:",
    fa_notFound: "❌ 가입된 계정이 없습니다.",
    fa_sent: "📧 메일을 보냈습니다!",
    findAccount: "아이디/비밀번호 찾기",

    // ==================== 📝 게시판 (Board) ====================
    bd_title: "📢 테토카페(시즌3)",
    bd_no_posts: "아직 작성된 글이 없습니다.",
    bd_write_btn: "🖊️ 글쓰기",
    bd_notice: "공지",
    bd_hot: "HOT",
    bd_new_title: "🖊️ 새 글 쓰기",
    bd_edit_title: "📝 글 수정하기",
    bd_input_title: "제목을 입력하세요",
    bd_input_content: "내용을 자유롭게 적어주세요...",
    bd_file: "📸 사진 첨부 (선택)",
    bd_uploading: "업로드 중... ⏳",
    bd_submit: "등록하기",
    bd_edit_complete: "수정 완료",
    bd_admin_notice: "📢 공지사항 등록",
    bd_like: "좋아요",
    bd_comments: "댓글",
    bd_comment_input: "댓글을 입력하세요...",
    bd_register: "등록",
    bd_delete: "삭제",
    bd_edit: "수정",
    bd_delete_confirm: "정말 삭제하시겠습니까?",
    bd_reply: "답글",
    bd_reply_input: "답글을 입력하세요...",
    bd_like_comment: "좋아요",
    bd_cancel_reply: "답글 취소",
    alertLoginReq: "로그인이 필요합니다.",
    alertInputAll: "제목과 내용을 입력하세요.",
    bd_img_url: "📸 이미지 주소 (URL) 또는 유튜브 링크",
    bd_url_ph: "예: https://youtu.be/... 또는 https://site.com/image.jpg",
    bd_url_desc: "* 구글 등에서 '이미지 주소 복사' 후 붙여넣으세요.",
    bd_saving: "저장 중...",
    bd_tab_free: "💬 자유",
    bd_tab_humor: " 📝교양",
    bd_tab_yoon: "👑 윤갤",
    bd_select_board: "게시판 선택",
    bd_cat_free: "💬 자유 갤러리",
    bd_cat_humor: "🤣 교양 갤러리",
    bd_cat_yoon: "👑 윤 갤러리",
    bd_more: "👇 더 보기 (More)",

    // ==================== 🎲 기타 미니게임 (Mini Games) ====================
    slotSpin: "레버 당기기 (Spin)",
    slotJackpot: "🔥 잭팟!!",
    rouletteSpin: "돌리기 (SPIN!)",
    rouletteTitle: "🎡 ROULETTE",
    rouletteSelect: "어디에 걸지 선택하세요! (색깔 또는 숫자)",
    rouletteResult: "결과",
    angel: "천사",
    demon: "악마",
    rpsRock: "바위",
    rpsPaper: "보",
    rpsScissors: "가위",
    appleDesc: "드래그해서 합을 10으로 만드세요!",
    reactionTitle: "반응속도 테스트",
    reactionDesc: "화면이 초록색이 되면 클릭하세요!",
    ladderTitle: "🪜 네임드 사다리",
    lad_odd: "홀",
    lad_even: "짝",
    lad_left: "좌",
    lad_right: "우",
    lad_3line: "3줄",
    lad_4line: "4줄",
    lad_single: "홀/짝",
    lad_combo: "조합",
    lad_select: "배팅 항목을 선택하세요!",
    fightTitle: "🥊 UNDERGROUND FIGHT",
    f_red: "레드팀",
    f_blue: "블루팀",
    f_select: "응원할 파이터를 선택하세요!",
    f_start: "경기 시작 (START)",
    f_log_start: "🔔 1라운드 - FIGHT!",
    f_attack: "공격!",
    f_crit: "치명타!!",
    f_dodge: "회피 성공!",
    f_win: "경기 종료! 승리!",
    horseTitle: "🏇 SUPER DERBY",
    h_select: "우승 예상마를 선택하세요!",
    h_start: "START RACE",
    h_comm_start: "🔫 탕! 출발했습니다!",
    h_comm_mid: "치열한 선두 싸움!",
    h_comm_end: "결승선이 코앞입니다!",
    h_win: "우승! 적중!!",
    h_fail: "우승... 아쉽습니다.",
    gachaTitle: "GACHA MACHINE",
    g_pull: "뽑기 !",
    g_wait: "쿨타임...",
    probTable: "📊 확률 및 당첨금",
    g_god: "🌌 신 (GOD)",
    g_mythic: "🏴‍☠️ 신화 (Mythic)",
    g_legend: "💎 전설 (Legend)",
    g_epic: "👑 에픽 (Epic)",
    g_common: "💊 일반 (Common)",
    g_congrats: "축하합니다!",
    bjTitle: "🃏 BLACKJACK",
    bj_dealer: "딜러",
    bj_player: "나 (Player)",
    bj_hit: "히트 (카드 받기)",
    bj_stand: "스탠드 (멈추기)",
    bj_bust: "💥 버스트! 패배했습니다.",
    bj_ask: "카드를 더 받으시겠습니까?",
    mnTitle: "💣 MINES (지뢰 찾기)",
    mn_mines: "지뢰 수",
    mn_count: "개",
    mn_found: "개 찾음",
    mn_cashout: "원 챙기기",
    mn_boom: "쾅! 지뢰 폭발...",
    mn_retry: "다시 도전",
    mn_oneMore: "한 번 더?",
    crTitle: "🚀 CRASH GRAPH",
    cr_auto: "자동 익절 (예: 2.0)",
    cr_stop: "✋ STOP (익절)",
    cr_boom: "💥 폭발!",
    cr_retry: "🚀 다시 발사",
    cr_odds: "📊 배당별 확률",
    hlTitle: "🃏 HIGH-LOW",
    hl_rule: "📜 게임 규칙",
    hl_high: "⬆️ HIGH (높음)",
    hl_low: "⬇️ LOW (낮음)",
    hl_success: "성공!",
    hl_fail: "땡! 패배했습니다.",
    hl_cashout: "돈 챙기기",
    hl_current: "현재 배당",
    hl_profit: "현재 수익",

    // 🔥 [추가] 산와머니 (대출)
    loan_title: "💸 강산와머니",
    loan_subtitle: "빠르고 간편한 무심사 대출 서비스",
    loan_warning: "선이자 20% • 기한 1일",
    my_debt: "현재 빚 (Debt)",
    loan_limit: "대출 가능",
    btn_borrow: "빌리기",
    btn_repay: "갚기",
    loan_msg_borrow: "얼마나 필요하신가요?",
    loan_msg_repay: "얼마를 갚으시겠어요?",
    placeholder_amount: "금액 입력",
    btn_execute_borrow: "💰 대출 실행 (선이자 10%)",
    btn_execute_repay: "💸 빚 청산하기",
    loan_rank_title: "😈 고액 체납자 명단",
    loan_no_debtors: "아직 빚쟁이가 없습니다.",
    loan_alert_input: "금액을 정확히 입력해주세요.",
    loan_alert_limit: "🚫 대출 한도 초과!",
    loan_alert_no_point: "상환할 포인트가 부족합니다.",
    loan_alert_too_much: "갚을 빚보다 많은 금액입니다.",
    loan_success_borrow: "💰 입금 완료! (선이자 차감됨)",
    loan_success_repay: "✅ 상환 완료!",
    loan_forgive: "탕감",
    loan_forgive_done: "탕감 처리 완료"
  },
  jp: {
    // ==================== 🏠 共通 UI (Common) ====================
    home: "🏠 ホーム",
    login: "ログイン",
    logout: "ログアウト",
    signup: "会員登録",
    myWallet: "マイウォレット",
    balance: "保有資産",
    my_point: "保有資産", // 🔥 추가됨
    cancel: "キャンセル",
    confirm: "確認",
    close: "閉じる",
    loading: "読み込み中...",
    back: "戻る",
    serverCheck: "🚧 サーバー点検中",
    banned: "🚫 アカウント停止中",
    waitingApproval: "⏳ 承認待ち",
    inputEmail: "メールアドレス",
    inputPw: "パスワード",
    inputName: "名前 (ニックネーム)",
    fail: "失敗", // 🔥 추가됨
    success: "成功", // 🔥 추가됨

    // ==================== 👮 管理者 & 制裁 (Admin & Sanction) ====================
    ad_title: "👮 統合管理者ページ",
    ad_tab_notice: "📢 公知",
    ad_tab_users: "👥 ユーザー",
    ad_tab_sanction: "🚨 制裁",
    ad_tab_history: "📜 履歴",
    ad_tab_server: "🚧 サーバー",
    ad_tab_features: "⚙️ 機能",
    ad_tab_wishbox: "🧞‍♂️ 願い箱",
    
    ad_notice_title: "メインお知らせ設定",
    ad_notice_ph: "内容入力...",
    ad_save: "💾 保存",
    ad_report_rank: " 通報累積ランキング ",
    reset_report: "🔄 通報リセット",
    reset_report_confirm: "通報回数をすべて0にリセットしますか？",
    ad_no_report: "通報されたユーザーはいません。(クリーン)",
    ad_search_user: "ユーザー検索...",
    ad_report_cnt: "通報",
    ban_gacha: "ガチャ停止",
    ad_lift_ban: "停止解除",
    ad_state_banned: "⛔ 制裁中",
    ad_state_normal: "✅ 正常",
    ad_tier: "ランク",
    ad_demote: "降格",
    ad_promote: "昇格",
    ad_tier_change: "ランク変更",
    confiscate: "財産没収",
    ad_input_confiscate: "没収",
    ad_confiscate_amount: "没収する金額を入力してください",
    ad_input_num: "数字のみ入力してください",
    ad_total_asset: "サーバー総資産",
    ad_user_cnt: "現在加入ユーザー",
    ad_approve: "承認",
    ad_cancel_approve: "承認取消",
    ad_ban_confirm: "Ban/解除しますか？",
    ad_point_confirm: "ポイントを支給/差引しますか？",
    ad_server_status: "現在のサーバー状態",
    ad_open_server: "✅ サーバー開く",
    ad_close_server: "🛑 サーバー閉じる",
    ad_open_confirm: "サーバーを開きますか？",
    ad_close_confirm: "サーバーを閉じますか？",
    ad_feature_control: "システム機能制御",
    ad_refresh_all: "全ユーザー更新",
    ad_refresh_confirm: "全ユーザーに更新信号を送信しますか？",
    ad_history_title: "最近の取引履歴 (50件)",
    ad_confirm: "実行しますか",
    lift_date: "解除日時",
    gacha_banned_msg: "🚫 ガチャの利用が停止されています。",

    // 🔥 [추가] 管理者新規機能 (日本語)
    ad_wish_list: "届いた願い事",
    ad_no_wish: "届いた願い事はありません。",
    ad_audit_btn: "🔍 帳簿検査",
    ad_audit_suspicious: "🚨 操作疑惑!!",
    ad_audit_normal: "✅ 正常アカウント",
    ad_audit_diff: "誤差",
    ad_sync_posts: "🔄 掲示板ランク同期",
    ad_sync_confirm: "すべての掲示板の作成者情報を現在のユーザー情報で上書きします。",

    // ==================== 💰 ベッティング & 通貨 (Betting & Money) ====================
    inputBet: "ベット額を入力",
    alertInputBet: "ベット額を入力してください！",
    alertNoMoney: "ポイントが足りません！",
    alertError: "エラーが発生しました",
    h_bet: "ベット",
    h_gain: "獲得",
    h_result: "結果",

    // ==================== 🔔 通知 (Notification) ====================
    h_noti: "通知",
    h_no_noti: "新しい通知はありません。",
    alert_unread: "未読の通知が{n}件あります！",
    noti_clear: "通知をすべて消去",
    noti_clear_confirm: "すべての通知を削除しますか？",
    noti_like: "様があなたの投稿にいいねしました。",
    noti_comment: "様があなたの投稿にコメントしました。",
    noti_reply: "様があなたのコメントに返信しました。",

    // ==================== 🚫 制限 & ブロック (Limits) ====================
    daily_limit_msg: "今日の残りメッセージ: {n}回",
    daily_limit_report: "今日の残り通報: {n}回",
    limit_reached: "本日の回数をすべて使い切りました。",

    // ==================== 🔝 ヘッダー & メニュー (Header & Menu) ====================
    h_attack: "核攻撃",
    h_gacha: "ガチャ",
    h_transfer: "送金",
    h_history: "履歴",
    h_mailbox: "メッセージ",
    h_report: "通報",
    h_nuke_ask: "⚔️ 核爆弾を発射しますか？",
    h_nuke_desc: "全財産の半分を使用してランダムユーザー1名を攻撃します。",
    h_nuke_no_target: "攻撃対象がいません。",
    h_nuke_min: "核爆弾を発射するには最低100ウォン必要です。",
    h_nuke_hit: "🎯 [命中]",
    h_nuke_hit_msg: "様に核爆弾が落ちました！",
    h_nuke_damage: "ダメージ",
    h_locked: "🔒 現在、管理者がこの機能を無効にしています。",

    // ==================== 🎮 ゲームロビー (Game Lobby) ====================
    lobbyTitle: "🎮 ゲームロビー",
    roomTitlePlaceholder: "ルーム名を入力",
    betAmount: "ベット額",
    createRoom: "ルーム作成",
    waiting: "待機中のルームがありません。",
    enter: "入場する",
    full: "満員",
    participate: "参加する",
    g_omok: "⚫ 五目並べ",
    g_rps: "✌️ じゃんけん",
    g_soccer: "⚽ PK戦",
    g_typing: "⌨️ タイピング",
    g_memory: "🃏 神経衰弱",
    g_reaction: "⚡ 反応速度",
    g_apple: "🍎 リンゴゲーム",

    // ==================== 🎮 ゲーム共通 (Game Common) ====================
    gameZone: "🎮 ゲームゾーン",
    rank: "🏆 ランキング",
    updateRank: "🔄 更新",
    notice: "📢 ",
    adminOnly: "👑 管理者専用",
    adminPage: "👥 管理ページ",
    waitingChallenger: "👥 挑戦者 待機中...",
    deleteRoom: "ルーム削除",
    destroyRoom: "🏠 ルーム解散",
    playerJoined: "👋 参加者が入室しました！",
    readyBtn: "準備完了 (READY)",
    ready: "準備完了",
    cancelReady: "準備取消",
    waitingReady: "参加者の準備を待っています...",
    allReady: "✅ 準備完了！",
    gameStart: "ゲーム開始",
    restart: "もう一度",
    startWait: "ホストが開始するとゲームが始まります。",
    exit: "退出",
    win: "🎉 勝利！",
    draw: "引き分け！",
    lose: "敗北...",
    result: "結果",
    notEnough: "人数不足",
    oneMore: "🔄 もう一回",
    waitHost: "ホスト待機中...",
    waitUser: "参加者待機中...",

    // ==================== 🕹️ ゲーム名 (Game Names) ====================
    pvp: "⚔️ 1:1 (PvP)",
    cafe: "👑 テトカフェ",
    oddEven: "🎲 丁半",
    slot: "🎰 スロット",
    rps: "✌️ じゃんけん",
    blackjack: "🃏 ブラックジャック",
    angelDemon: "🎡 天使悪魔",
    ladder: "🎢 あみだくじ",
    mines: "💣 マインスイーパ",
    graph: "🚀 クラッシュ",
    highlow: "🃏 ハイロー",
    european: "🎡 ヨーロピアン",
    ostrich: "🦩 ダチョウ",
    apple: "🍎 リンゴゲーム",
    highway: "🚗 ハイウェイ・ラッシュ",
    stack: "🏗️ ネオン・スタック",
    newBadge: "NEW!",

    // 🔥 [추가] 2048 게임 (日本語)
    g_2048_title: "🧩 2048 チャレンジ",
    g_2048_desc: "タイルを合体させて高い数字を作ろう！",
    g_2048_rule: "ゲームオーバー時の「最大タイル」に応じて配当が支給されます。",
    g_2048_max: "最大タイル",
    g_2048_score: "スコア",
    g_2048_payout: "📊 配当表 (最大タイル基準)",
    g_2048_my_asset: "保有資産",
    g_2048_gameover: "ゲームオーバー",
    g_2048_win: "おめでとうございます！",
    g_2048_fail: "失敗...",

    // 🔥 [추가] 수박 게임 (日本語)
    g_suika_title: "🍉 スイカゲーム",
    g_suika_score: "スコア",
    g_suika_next: "次",
    g_suika_rule: "フルーツを合体させてスイカを作ろう！",

    // 🔥 [추가] 테트리스 (日本語)
    g_tetris_title: "🧱 テトリス",
    g_score: "スコア",
    g_level: "レベル",
    g_lines: "ライン",
    g_hold: "ホールド",
    g_next: "ネクスト",
    g_paused: "一時停止",
    g_resume: "再開する",
    playAgain: "もう一度",
    g_hold_btn: "ホールド (C)",
    g_drop_btn: "ドロップ (Spc)",
    g_paused_btn: "一時停止 (P)",
    probTable: "📊 配当表", // 🔥 추가됨

    // ==================== 🍏 リンゴゲーム (Apple Game) ====================
    ag_title: "🍏 リンゴチャレンジ",
    ag_bet: "1. ベット額",
    ag_diff: "2. 目標難易度",
    ag_start: "挑戦する",
    ag_goal: "目標",
    ag_score: "スコア",
    ag_success: "🎉 成功！",
    ag_fail: "😭 失敗..",
    ag_cheat: "🚫 不正行為検知！(時間操作)",
    ag_disqualify: "離脱による失格 (ポイント消滅)",

    // ==================== 🏆 ショップ (Shop) ====================
    shop: "🏆 ショップ",
    shopTitle: "🏆 ショップ",
    shopBalance: "保有資産",
    buy: "購入",
    nickChange: "🏷️ 名前変更券",
    nickDesc: "新しい名前に変更します。",
    blackMarket: "😈 闇市場",
    shopClosed: "🔒 闇市場は閉鎖されました",
    demoteR1: "📉 ランダム1段降格",
    demoteR2: "📉 ランダム2段降格",
    demoteSelf: "(自分含む)",
    demoteNoSelf: "(自分除く)",
    demoteBomb1: "💣 ランダム1段降格",
    demoteBomb2: "💣 ランダム2段降格",
    sniper: "🎯 狙撃降格",
    sniperDesc: "(名前指定 / 2段階ダウン)",
    sniperTitle: "🎯 ターゲット検索",
    searchNick: "名前入力",
    search: "🔍 検索",
    doDemote: "降格させる",
    noResult: "検索結果がありません。",
    currentTier: "現在のランク",
    upgrade: "昇格 ▲",
    alertNick: "新しい名前を入力してください:",
    alertCost: "費用",
    alertComplete: "完了！",
    alertTargetNone: "降格させる対象がいません。",
    alertSniperConfirm: "様を2段階降格させますか？",
    
    // 🔥 [추가] 소원권 관련 (일본어)
    wishTicket: "🧞‍♂️ 願いのチケット",
    wishDesc: "管理者に願いを伝えます。(全財産の50%)",
    wish_min_asset: "最低10億以上の資産が必要です。",
    wish_input_ph: "叶えたい願いを入力してください。",
    wish_confirm: "本当に願い事をしますか？",
    wish_success: "管理者に願いが送信されました！",

    // ==================== 💸 送金 (Transfer) ====================
    transferTitle: "💸 送金",
    transferDesc: "友達にポイントをプレゼントしましょう。",
    myBalance: "残高",
    searchReceiver: "受取人検索",
    searchPlaceholder: "名前の最初の文字を入力",
    searchBtn: "検索",
    select: "選択",
    sendAmount: "送金額",
    sendBtn: "送る 🚀",
    sending: "送金中...",
    alertSendConfirm: "様に",
    alertSendConfirm2: "ウォンを送りますか？",
    alertSelf: "自分には送れません。",
    alertNoReceiver: "受取人の名前を入力してください！",

    // ==================== 📬 メッセージ (Mailbox) ====================
    mb_title: "📬 メッセージ",
    mb_inbox: "受信トレイ",
    mb_sent: "送信トレイ",
    mb_write: "作成",
    mb_sender: "送信者",
    mb_receiver: "受信者",
    mb_content: "内容",
    mb_date: "日付",
    mb_read: "既読",
    mb_unread: "未読",
    mb_no_msg: "メッセージがありません。",
    mb_send_btn: "送信",
    mb_cancel: "取消",
    mb_search_user: "ユーザー検索 (名前)",
    mb_search_res: "検索結果",
    mb_send_success: "メッセージを送信しました！",
    mb_delete_confirm: "削除しますか？",
    mb_reply: "返信",
    mb_to: "へ",

    // ==================== 🚨 通報 (Report) ====================
    r_title: "🚨 悪質ユーザー通報",
    r_step1: "1. ユーザーを検索してください",
    r_step2: "2. 通報理由を選択してください",
    r_reason_input: "具体的な理由を入力してください...",
    r_submit: "通報する",
    r_complete: "通報を受け付けました。",
    r_prev: "戻る",
    r_target: "対象:",
    r_confirm_ask: "様を通報しますか？",
    r_reason_1: "暴言/誹謗",
    r_reason_2: "詐欺",
    r_reason_3: "スパム/宣伝",
    r_reason_4: "性的発言",
    r_reason_5: "直接入力",
    r_admin_fail: "管理者情報が見つかりません。",

    // ==================== 📜 履歴 (History) ====================
    history: "📜 履歴",
    log_gacha: "ガチャ",
    log_transfer: "送金",
    log_deposit: "入金",
    log_game: "ゲーム",
    log_attack: "攻撃",
    log_hit: "被撃",
    log_sniper: "狙撃",
    log_no_data: "履歴がありません。",

    // ==================== 🕵️ アカウント検索 (Find Account) ====================
    faTitle: "🕵️ アカウント検索",
    fa_findId: "ID検索",
    fa_findPw: "PW検索",
    fa_name: "登録した名前",
    fa_email: "登録したメール",
    fa_send: "再設定メール送信",
    fa_found: "✅ ID:",
    fa_notFound: "❌ アカウントが見つかりません。",
    fa_sent: "📧 メールを送信しました！",
    findAccount: "ID/PWを探す",

    // ==================== 📝 掲示板 (Board) ====================
    bd_title: "📢 テトカフェ (Season 3)",
    bd_no_posts: "まだ記事がありません。",
    bd_write_btn: "🖊️ 作成",
    bd_notice: "公知",
    bd_hot: "HOT",
    bd_new_title: "🖊️ 新しい記事",
    bd_edit_title: "📝 記事修正",
    bd_input_title: "タイトルを入力",
    bd_input_content: "内容を自由に入力してください...",
    bd_file: "📸 画像添付 (任意)",
    bd_uploading: "アップロード中... ⏳",
    bd_submit: "登録する",
    bd_edit_complete: "修正完了",
    bd_admin_notice: "📢 お知らせ登録",
    bd_like: "いいね",
    bd_comments: "コメント",
    bd_comment_input: "コメントを入力...",
    bd_register: "登録",
    bd_delete: "削除",
    bd_edit: "修正",
    bd_delete_confirm: "本当に削除しますか？",
    bd_reply: "返信",
    bd_reply_input: "返信を入力...",
    bd_like_comment: "いいね",
    bd_cancel_reply: "返信取消",
    alertLoginReq: "ログインが必要です。",
    alertInputAll: "タイトルと内容を入力してください。",
    bd_img_url: "📸 画像URL または YouTubeリンク",
    bd_url_ph: "例: https://youtu.be/... または https://site.com/image.jpg",
    bd_url_desc: "* Googleなどで「画像アドレスをコピー」して貼り付けてください。",
    bd_saving: "保存中...",
    bd_tab_free: "💬 自由",
    bd_tab_humor: "🤣 ユーモア",
    bd_tab_yoon: "👑 ユンギャル",
    bd_select_board: "掲示板選択",
    bd_cat_free: "💬 自由掲示板",
    bd_cat_humor: "🤣 ユーモア掲示板",
    bd_cat_yoon: "👑 ユンギャル掲示板",
    bd_more: "👇 もっと見る (More)",

    // ==================== 🎲 ミニゲーム (Mini Games) ====================
    slotSpin: "スピン (Spin)",
    slotJackpot: "🔥 大当たり!!",
    rouletteSpin: "回す (SPIN!)",
    rouletteTitle: "🎡 ルーレット",
    rouletteSelect: "賭ける場所を選んでください！(色または数字)",
    rouletteResult: "結果",
    angel: "天使",
    demon: "悪魔",
    rpsRock: "グー",
    rpsPaper: "パー",
    rpsScissors: "チョキ",
    appleDesc: "ドラッグして合計を10にしてください！",
    reactionTitle: "反応速度テスト",
    reactionDesc: "画面が緑になったらクリック！",
    ladderTitle: "🪜 あみだくじ",
    lad_odd: "奇",
    lad_even: "偶",
    lad_left: "左",
    lad_right: "右",
    lad_3line: "3本",
    lad_4line: "4本",
    lad_single: "奇/偶",
    lad_combo: "組合せ",
    lad_select: "賭ける項目を選択してください！",
    fightTitle: "🥊 地下闘技場",
    f_red: "赤チーム",
    f_blue: "青チーム",
    f_select: "応援する選手を選んでください！",
    f_start: "試合開始 (START)",
    f_log_start: "🔔 第1ラウンド - FIGHT!",
    f_attack: "攻撃！",
    f_crit: "クリティカル！！",
    f_dodge: "回避成功！",
    f_win: "試合終了！勝利！",
    horseTitle: "🏇 SUPER DERBY",
    h_select: "優勝馬を予想してください！",
    h_start: "START RACE",
    h_comm_start: "🔫 パン！一斉にスタート！",
    h_comm_mid: "激しい先頭争い！",
    h_comm_end: "ゴールは目の前だ！",
    h_win: "優勝！的中！！",
    h_fail: "優勝... 残念です。",
    gachaTitle: "GACHA MACHINE",
    g_pull: "ガチャる !",
    g_wait: "쿨타임...",
    probTable: "📊 確率一覧",
    g_god: "🌌 神 (GOD)",
    g_mythic: "🏴‍☠️ 神話 (Mythic)",
    g_legend: "💎 伝説 (Legend)",
    g_epic: "👑 エピック (Epic)",
    g_common: "💊 一般 (Common)",
    g_congrats: "おめでとうございます！",
    bjTitle: "🃏 BLACKJACK",
    bj_dealer: "ディーラー",
    bj_player: "自分 (Player)",
    bj_hit: "ヒット (引く)",
    bj_stand: "スタンド (勝負)",
    bj_bust: "💥 バースト！ 敗北...",
    bj_ask: "カードを引きますか？",
    mnTitle: "💣 MINES (地雷探し)",
    mn_mines: "地雷数",
    mn_count: "個",
    mn_found: "個発見",
    mn_cashout: "円 獲得",
    mn_boom: "ドカン！ 地雷爆発...",
    mn_retry: "再挑戦",
    mn_oneMore: "もう一度？",
    crTitle: "🚀 CRASH GRAPH",
    cr_auto: "自動利食い (例: 2.0)",
    cr_stop: "✋ STOP (利食い)",
    cr_boom: "💥 爆発！",
    cr_retry: "🚀 再発射",
    cr_odds: "📊 倍率別確率",
    hlTitle: "🃏 HIGH-LOW",
    hl_rule: "📜 ルール",
    hl_high: "⬆️ HIGH (高い)",
    hl_low: "⬇️ LOW (低い)",
    hl_success: "成功！",
    hl_fail: "ハズレ！敗北...",
    hl_cashout: "お金を獲得",
    hl_current: "現在の倍率",
    hl_profit: "現在の収益",

    // 🔥 [추가] サンワマネー (ローン)
    loan_title: "💸 サンワマネー",
    loan_subtitle: "迅速かつ簡単な無審査ローンサービス",
    loan_warning: "先利子 20% • 期限 1日",
    my_debt: "現在の借金 (Debt)",
    loan_limit: "融資可能額",
    btn_borrow: "借りる",
    btn_repay: "返す",
    loan_msg_borrow: "いくら必要ですか？",
    loan_msg_repay: "いくら返済しますか？",
    placeholder_amount: "金額を入力",
    btn_execute_borrow: "💰 融資実行 (先利子 10%)",
    btn_execute_repay: "💸 借金返済",
    loan_rank_title: "😈 多額滞納者リスト",
    loan_no_debtors: "まだ借金をしている人はいません。",
    loan_alert_input: "金額を正確に入力してください。",
    loan_alert_limit: "🚫 融資限度額を超過しました！",
    loan_alert_no_point: "返済するポイントが足りません。",
    loan_alert_too_much: "返済額が借金を超えています。",
    loan_success_borrow: "💰 融資完了！(先利子が差し引かれました)",
    loan_success_repay: "✅ 返済完了！",
    loan_forgive: "免除",
    loan_forgive_done: "免除完了"
  }
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('ko');
  const t = translations[lang];
  const toggleLang = () => setLang(prev => prev === 'ko' ? 'jp' : 'ko');

  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}